# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: abnmt.theaternews::lang.news.label

# Model Form Field configuration
form: $/abnmt/theaternews/models/news/fields.yaml

# Model Class name
modelClass: Abnmt\TheaterNews\Models\News

# Default redirect location
defaultRedirect: abnmt/theaternews/news

# Create page
create:
    title: abnmt.theaternews::lang.news.create_title
    redirect: abnmt/theaternews/news/update/:id
    redirectClose: abnmt/theaternews/news

# Update page
update:
    title: abnmt.theaternews::lang.news.update_title
    redirect: abnmt/theaternews/news
    redirectClose: abnmt/theaternews/news

# Preview page
preview:
    title: abnmt.theaternews::lang.news.preview_title